---

- name: Cisco Unified Config
  connection: local
  hosts: all
  gather_facts: false
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      auth_pass: "{{ secret }}"
      authorize: "{{ use_secret }}"
      timeout: "{{ timeout }}"

  roles:
    - role: ber
      when: inventory_hostname | search ("ber")
