---

- name: Add Repository [RedHat]
  yum: name={{ item }} state=present
  with_items: "https://yum.puppet.com/puppet5/puppet5-release-el-{{ ansible_distribution_major_version }}.noarch.rpm"


- name: Install Puppet Agent [RedHat]
  apt: name={{ item }}  state=present
  with_items: "puppet-agent-{{ puppet_agent_version }}-1.el{{ ansible_distribution_major_version }}"
